### ISSUE TITLE
TODO tutorial, db studio command errors with prisma **ECONNREFUSED**

### ISSUE THREAD

**Issue by philderbeast** [wasp-lang/wasp#356]
I'm running through the TODO tutorial and hit this problem with `wasp db studio` when looking at the Tasks table:

![Screen Shot 2021-11-10 at 11 19 22 AM](https://user-images.githubusercontent.com/633283/141151688-9c4a458f-c989-403c-8730-59dd156794e6.png)

Following the tutorial's [task entity page](https://wasp-lang.dev/docs/tutorials/todo-app/task-entity), I added `entity Task` and did the db migration.

```
# main.wasp
app App {
  title: "TODOs"
}

route "/" -> page Main
page Main {
  component: import Main from "@ext/MainPage.js"
}

entity Task {=psl
  id Int @id @default(autoincrement())
  description String
  isDone Boolean @default(false)
psl=}
```

```
> wasp db migrate-dev
Compiling wasp code...
Code has been successfully compiled, project has been generated.


Setting up database...

Server:
Server: up to date, audited 428 packages in 1s
Server:
Server: 61 packages are looking for funding
Server:   run `npm fund` for details
Server:
Server: 6 moderate severity vulnerabilities
Server:
Server: To address all issues (including breaking changes), run:
Server:   npm audit fix --force
Server:
Server: Run `npm audit` for details.
Server:
Database successfully set up!
Copying migrations folder from Wasp to Prisma project...
Done copying migrations folder.
Performing migration...
Prisma schema loaded from ../db/schema.prisma
Datasource "db": SQLite database "dev.db" at "file:./dev.db"

SQLite database dev.db created at file:./dev.db

✔ Name of migration … Add Task
The following migration(s) have been created and applied from new schema changes:

migrations/
  └─ 20211110161115_add_task/
    └─ migration.sql

Your database is now in sync with your schema.

Running generate... (Use --skip-generate to skip the generators)

added 2 packages, and audited 3 packages in 2s

found 0 vulnerabilities

added 2 packages, and audited 5 packages in 3s

found 0 vulnerabilities

✔ Generated Prisma Client (2.22.1) to ./node_modules/.prisma/client in 150ms


Migration done.
Copying migrations folder from Prisma to Wasp project...
Done copying migrations folder.
All done!
> wasp db studio
Compiling wasp code...
Code has been successfully compiled, project has been generated.


Setting up database...

Server:
Server: up to date, audited 428 packages in 2s
Server:
Server: 61 packages are looking for funding
Server:   run `npm fund` for details
Server:
Server: 6 moderate severity vulnerabilities
Server:
Server: To address all issues (including breaking changes), run:
Server:   npm audit fix --force
Server:
Server: Run `npm audit` for details.
Server:
Database successfully set up!
Running studio...

Db: Prisma schema loaded from ../db/schema.prisma
Db: Prisma Studio is up on http://localhost:5555
Db: ┌─────────────────────────────────────────────────────────┐
Db (stderr): │  Update available 2.22.1 -> 3.4.2                       │
Db (stderr): │  Run the following to update                            │
Db (stderr): │    npm i --save-dev prisma                              │
Db (stderr): │    npm i @prisma/client                                 │
Db (stderr): └─────────────────────────────────────────────────────────┘
Db (stderr):
```

```
> sw_vers
ProductName:	macOS
ProductVersion:	11.6.1
BuildVersion:	20G224
```

**Comment by Martinsos** [comment]
Hmmmm, it says ECONNREFUSED.

One possible cause might be that our Prisma version is old, and that updating it would fix this -> we haven't done much work on this part lately but we will be working on it much more in the near future. We have version of Prisma fixed, so in theory this shouldn't happen, but I noticed that in practice it does.

Since you are using SQLite database at this point, there is no database to connect to, so I wonder what is the "connection refused" about. I believe there is some kind of Prisma engine that is used by prisma studio so maybe problem comes there from some mismatch in versions - shouldn't be happening, but that might be it.

Anyway, thanks for pointing this out - I think the best way to proceed is to update Prisma, which I will take a go at, and then I will let you know how that goes. I am not sure how much it changed from version 2 to version 3, so I will have to consult their changelog. It shouldn't affect us for the most parts, but we do also have parser that parses their PSL language so that might need some adjusting.

**Comment by shayneczyzewski** [comment]
Hi @philderbeast and @Martinsos. I gave this a quick run through on my Mac and was unfortunately not able to reproduce that exact error (but found something else):

```
app TodoApp { // Main declaration, defines a new web app.
  title: "TodoApp" // Used as a browser tab title.
}

route "/" -> page Main // Render page Main on url `/` (default url).

page Main {
  // We specify that ReactJS implementation of our page can be
  // found in `ext/MainPage.js` as a default export (uses standard
  // js import syntax).
  component: import Main from "@ext/MainPage.js"
}

entity Task {=psl
    id          Int     @id @default(autoincrement())
    description String
    isDone      Boolean @default(false)
psl=}
```

```
  │  /tmp/Repro  wasp db migrate-dev                                                            ✔ │ 8s 
Compiling wasp code...
Code has been successfully compiled, project has been generated.


Setting up database...

Server:
Server: up to date, audited 428 packages in 1s
Server:
Server: 61 packages are looking for funding
Server:   run `npm fund` for details
Server:
Server: 6 moderate severity vulnerabilities
Server:
Server: To address all issues (including breaking changes), run:
Server:   npm audit fix --force
Server:
Server: Run `npm audit` for details.
Server:
Database successfully set up!
Copying migrations folder from Wasp to Prisma project...
Done copying migrations folder.
Performing migration...
Prisma schema loaded from ../db/schema.prisma
Datasource "db": SQLite database "dev.db" at "file:./dev.db"

✔ Name of migration … test
The following migration(s) have been created and applied from new schema changes:

migrations/
  └─ 20211220152148_test/
    └─ migration.sql

Your database is now in sync with your schema.

Running generate... (Use --skip-generate to skip the generators)

added 2 packages, and audited 3 packages in 1s

found 0 vulnerabilities

added 2 packages, and audited 5 packages in 776ms

found 0 vulnerabilities

✔ Generated Prisma Client (2.22.1) to ./node_modules/.prisma/client in 107ms


Migration done.
Copying migrations folder from Prisma to Wasp project...
Done copying migrations folder.
All done!

  │  /tmp/Repro  wasp db studio                                                                 ✔ │ 9s 
Compiling wasp code...
Code has been successfully compiled, project has been generated.


Setting up database...

Server:
Server: up to date, audited 428 packages in 1s
Server:
Server: 61 packages are looking for funding
Server:   run `npm fund` for details
Server:
Server: 6 moderate severity vulnerabilities
Server:
Server: To address all issues (including breaking changes), run:
Server:   npm audit fix --force
Server:
Server: Run `npm audit` for details.
Server:
Database successfully set up!
Running studio...

Db: Prisma schema loaded from ../db/schema.prisma
Db: Prisma Studio is up on http://localhost:5555
Db: ┌─────────────────────────────────────────────────────────┐
Db (stderr): │  Update available 2.22.1 -> 3.6.0                       │
Db (stderr): │  Run the following to update                            │
Db (stderr): │    npm i --save-dev prisma                              │
Db (stderr): │    npm i @prisma/client                                 │
Db (stderr): └─────────────────────────────────────────────────────────┘
```

Which is strange, since our terminal outputs look the same. But my command opens a new browser tab and loads that part fine:

![Screen Shot 2021-12-20 at 10 22 21 AM](https://user-images.githubusercontent.com/523636/146791545-84ce5f81-0c0d-46d7-8760-3f1b18b6283d.png)

I even added one to see if that worked, and stopped and restarted db studio several times:
![Screen Shot 2021-12-20 at 10 32 16 AM](https://user-images.githubusercontent.com/523636/146792482-7f3cf514-d94d-4c71-b744-305f481718d6.png)

The one thing I did notice is if I refresh http://localhost:5555 in the window db studio automatically opened (or paste that URL into a new tab/browser) I do get the following error in the console:
```
Db: Prisma schema loaded from ../db/schema.prisma
Db: Prisma Studio is up on http://localhost:5555
Db: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Db (stderr): TypeError: Converting circular structure to JSON
Db (stderr):     --> starting at object with constructor 'Object'
Db (stderr):     |     property 'fields' -> object with constructor 'Array'
Db (stderr):     |     index 0 -> object with constructor 'Object'
Db (stderr):     |     ...
Db (stderr):     |     index 0 -> object with constructor 'Object'
Db (stderr):     --- property 'type' closes the circle
Db (stderr):     at JSON.stringify (<anonymous>)
Db (stderr):     at serialize (/private/tmp/Repro/.wasp/out/server/node_modules/prisma/build/index.js:131814:17)
Db (stderr):     at HTTPNodeTransport.respond (/private/tmp/Repro/.wasp/out/server/node_modules/prisma/build/index.js:131829:34)
Db (stderr):     at /private/tmp/Repro/.wasp/out/server/node_modules/prisma/build/index.js:140730:29
Db (stderr):     at processTicksAndRejections (internal/process/task_queues.js:93:5)
Db (stderr):
```

And I get a WSOD in the UI, but I am not sure if that is related to what you saw Phil or not. It can be fixed by killing the command and restarting db studio, however, and letting the command open a new browser window for you.

![Screen Shot 2021-12-20 at 10 33 37 AM](https://user-images.githubusercontent.com/523636/146792848-4e6d10ba-58f6-43db-ab4b-90859684289e.png)

Do you get a new browser automatically opened for you when you run `wasp db studio` @philderbeast? And if so, is that where you see your error immediately?

We could be hitting two different snags, but I wanted to report I can get it working if I used the tab the command opens and do not refresh or open that URL in a different tab. Thanks for the additional info to help us try and figure it out!

**Comment by Martinsos** [comment]
Hm very interesting @shayneczyzewski !

It might be good to update Prisma first, since we are pretty behind (we have issue for updating it) and then come back to this, see if it is still happening.

**Comment by shayneczyzewski** [comment]
Yes I agree, we should probably spend our time upgrading Prisma first. Hopefully both issues will be resolved once done! 🤞🏻
