### ISSUE TITLE
Make semantics of operations' `entities` field more intuitive

### ISSUE THREAD

**Issue by sodic** [wasp-lang/wasp#967]
This:
```css
query getFoo {
  fn: import { getFoo } from "@server/queries.js",
  entities: []
}
```
Behaves the same as this
```css
query getFoo {
  fn: import { getFoo } from "@server/queries.js",
}
```
Both example cause Wasp to break with the following error (probably because Wasp assumes we want to use the database in every query):
```
Server(stderr): Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
Server(stderr): In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
Server(stderr):     at new PrismaClient (/home/filip/Projects/wasp/wasp/waspc/examples/filip-query-types/.wasp/out/server/node_modules/.prisma/client/index.js:3:11)
Server(stderr):     at createDbClient (file:///home/filip/Projects/wasp/wasp/waspc/examples/filip-query-types/.wasp/out/server/dist/dbClient.js:3:26)
Server(stderr):     at file:///home/filip/Projects/wasp/wasp/waspc/examples/filip-query-types/.wasp/out/server/dist/dbClient.js:6:18
Server(stderr):     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
Server(stderr):     at async Promise.all (index 0)
Server(stderr):     at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
Server(stderr):     at async loadESM (node:internal/process/esm_loader:91:5)
Server(stderr):     at async handleMainPromise (node:internal/modules/run_main:65:12)
```
When a Query doesn't use entities, we shouldn't be involving the database. To make matters worse, you can't even apply the migration without having entities, meaning that if you want a Wasp project without a database, you're stuck. The same applies to Actions.

**Comment by sodic** [comment]
Duplicate of #398
